# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [1]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [18]:
arr1 = np.ones((10))
print(arr1)

arr2 = np.arange(1, 21, 1, dtype="int")
print(arr2)

arr3 = np.ones((5, 5))
print(arr3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [27]:
arr4 = np.random.randn(3, 3, 3)
print(arr4)

arr4b = arr4.reshape(27)

[[[ 0.09851582  0.73947911  1.39254322]
  [ 0.375521   -0.28024223 -1.95736764]
  [ 3.42820834 -0.86282437 -0.95120736]]

 [[ 0.23860242 -1.5957904   0.16984437]
  [-0.36858054 -0.78683749  0.07559269]
  [-0.11135661  0.12442449 -0.98792322]]

 [[ 0.82071352  1.59528567  0.94936463]
  [ 1.05367572 -1.20535948 -1.59646781]
  [ 0.46558752  0.9144261   0.30474232]]]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [47]:
arr5 = np.arange(1, 10, 0.5, dtype="int")
print(arr5)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [82]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
20

In [80]:
print(a[1:5,3:5])

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [84]:
print(a[1])

[ 6  7  8  9 10]


```python
array([ 6,  7,  8,  9, 10])
```

In [86]:
print(a[3, 4])

20


## 2.5 

Calculate the sum of all the numbers in `a`.

In [81]:
sum_a = np.sum(a)
print(sum_a)

325


## 2.6 

Calculate the sum of each row in `a`.

In [92]:
sum_row0 = np.sum(a[0])
print(sum_row0)

sum_row1 = np.sum(a[1])
print(sum_row1)

sum_row2 = np.sum(a[2])
print(sum_row2)

sum_row2 = np.sum(a[2])
print(sum_row0)

sum_row2 = np.sum(a[2])
print(sum_row2)

15
40
65
15
65


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [93]:
print(325/25)

a_bool = a > 13
print (a_bool)

13.0
[[False False False False False]
 [False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [55]:
import numpy as np
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [68]:
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"
df = pd.read_csv(url, sep=",", header=0)

print(df.head(5))

     country food_category  consumption  co2_emmission
0  Argentina          Pork        10.51          37.20
1  Argentina       Poultry        38.66          41.53
2  Argentina          Beef        55.48        1712.00
3  Argentina   Lamb & Goat         1.56          54.63
4  Argentina          Fish         4.36           6.96


## 2.10 

How many rows and columns are there in the dataframe?

In [71]:
print("The data frame has this many rows")
print(len(df))

The data frame has this many rows
1430


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [78]:
print(df.columns)

Index(['country', 'food_category', 'consumption', 'co2_emmission'], dtype='object')


In [74]:
co2_mean = df["co2_emmission"].mean()
print(co2_mean)

74.383993006993


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [77]:
co2_max = df["co2_emmission"].max()
print(co2_max)

food_stats = pd.DataFrame()
food_stats = df.groupby("country")["co2_emmission"].max()
food_stats = df.groupby("food_category")["co2_emmission"].max()
food_stats

1712.0


food_category
Beef                        1712.00
Eggs                          17.59
Fish                         286.94
Lamb & Goat                  739.62
Milk - inc. cheese           613.57
Nuts inc. Peanut Butter       40.76
Pork                         237.54
Poultry                       67.14
Rice                         219.76
Soybeans                       7.63
Wheat and Wheat Products      37.66
Name: co2_emmission, dtype: float64

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

## 2.14

Which country consumes the least amount of beef per person per year?


In [ ]:
# code comes here

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [ ]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.